### ISSUE TITLE
shift-use_main not working for various blocks when offhand not empty

### ISSUE THREAD

**Issue by 4rz0** [AlgorithmX2/Ambidextrous#2]
Using shift-rightclick with rightlick being "use" for the mainhand doesn't trigger some block's special function when the offhand is not empty.
Affected are for example the Botania Runic Altar and the Mekanism Cardboard Box.
When the offhand is empty, the blocks work as intended.

**Comment by AlgorithmX2** [comment]
Give https://minecraft.curseforge.com/projects/ambidextrous/files/2347379 a try I believe it should resolve both issues.

**Comment by 4rz0** [comment]
Looking good, a quick test in SSP didn't have the problem anymore.

**Comment by AlgorithmX2** [comment]
Sounds like its fixed then, I'll go ahead and close this.
