### ISSUE TITLE
Uh.. Not sure how to use the mod

### ISSUE THREAD

**Issue by NovaViper** [AlgorithmX2/Ambidextrous#3]
I'm having problems trying to use the mod to set my key binds.. Not sure what I'm doing wrong. Can you tell me how do I use the mod?

**Comment by AlgorithmX2** [comment]
The mod adds 2 keybinds inside the normal MC Keybinds screen, you simply need to change them inside of there.

**Comment by NovaViper** [comment]
Strange.. I don't see that, I have the Controlling mod along with several other mods aswell with this one. The Controlling mod is the one that acutally modifies the key binding screen.. wonder if that's what causing the problem

**Comment by NovaViper** [comment]
Oh nvm, I found it!
