### ISSUE TITLE
Use Main Hand not working with sponge

### ISSUE THREAD

**Issue by 4rz0** [AlgorithmX2/Ambidextrous#4]
The "Use Main Hand" feature is not working on a server that has sponge installed.
Blocks get placed and removed from inventory, but instantly get removed from world. The blocks appear back in the player inventory after a refresh.
Minecraft's "Use Item/Place Block" does work as expected.
"Use Off Hand" does work as expected.

Issue 100% reproducable with following setup:
Minecraft Version 1.12
Server running recommended forge 14.23.5.2768, recommended stable spongeforge 2768-7.1.4, Version 1.2 of ambidextrous mod.
Client running recommended forge 14.23.5.2768, Version 1.2 of ambidextrous mod.
Minecraft's "Use Item/Place Block" button set to NONE, ambidextrous' "Use Main Hand" button set to Right Click, "Use Off Hand" set to F.

**Comment by AlgorithmX2** [comment]
Seems like Sponge has already fixed the issue.

**Comment by 4rz0** [comment]
I can confirm that, it works with latest stable spongeforge (1.12.2-2768-7.1.5-RC3540).
